### ISSUE TITLE
Missing Textures with Linux

### ISSUE THREAD

**Issue by ghost** [skaiTF/skyhud#2]
Hi!
So I installed the hud from gamebanana, and started the game as usual and saw Missing Texture Placeholders on some parts of the hud.

Screenshot Showcase:

![image](https://user-images.githubusercontent.com/81704775/147841087-33bbb0a1-aa83-41f5-8d30-dc7514cc44eb.png)
![image](https://user-images.githubusercontent.com/81704775/147841092-53cb9d0c-2f2e-41cd-b24f-8220fa425afc.png)

That's all i could find by myself.

**Comment by skaiTF** [comment]
HUD's working fine on my end, so it's likely an issue with your copy or with your tf2 installation. Have you changed the HUD in any way or did it come like this from gamebanana? Try re-downloading the HUD from gamebanana or from this repo if you haven't already. You can also try to verify your game files using steam as some texture files could be missing, but from the screenshot you added, it looks like the HUD's "materials" folder is missing or is at least corrupted. Provide more details if you can and if you happen to need extra help, feel free to message me on discord.

**Comment by skaiTF** [comment]
I think I might have figured it out. Whereas files in windows do not care about using capital letters, linux is case sensitive and needs every file to be lowercase in order to be loaded. Both of the textures you are missing have names with caps so I changed it to be all in lower case. Please try to download this last commit and see if the issue is fixed. Also, I must say that this HUD is not fully optimized for linux yet so you can expect some issues mainly with fonts being cut off in certain situations.

**Comment by ghost** [comment]
Ok, many thanks and Happy New Year!

**Comment by ghost** [comment]
I also found a folder in /materials/vgui/replay/thumbnails/ which had an uppercase letter. It turns out by changing "Menu" to "menu" fixed the problem.

**Comment by skaiTF** [comment]
Thank you, I tought I had changed the folder name in yesterday's commit but i guess my 1 am brain didn't quite get the job done. Btw, I don't really have a way to test the HUD on Linux right now, so if you end up facing more issues I'd really appreciate it if you could report them.
