### ISSUE TITLE
Minor issues in SkyHUD.

### ISSUE THREAD

**Issue by nternalz34** [skaiTF/skyhud#4]
Yes, this is on SkyHUD _latest_. (Though not important, but it's best to let it fixed in the next update for better experience 👍 .)

- Custom crosshairs not working, due to #base - crosshair.res not importing in "hudlayout.res" (README.txt didn't mention about this, at all.) 
![image](https://user-images.githubusercontent.com/102655447/161419235-2f95127d-638f-45da-85fb-f6359511698b.png)
- "Mode Selection" text missing compared to the screenshot album.
![2022-04-03 15_26_02-Team Fortress 2](https://user-images.githubusercontent.com/102655447/161419282-f58dc40f-4840-4d03-9da4-4dff27228a09.png)
- I don't even need to explain this.
![2022-04-03 15_27_11-Team Fortress 2](https://user-images.githubusercontent.com/102655447/161419342-34c0699c-ce10-47c6-bbce-cd8316749bd4.png)

**Comment by skaiTF** [comment]
Thanks for opening this issue, it really helps a lot to find out the dumb stuff I do sometimes lol.
As for the first problem with the crosshairs, I had already fixed it but forgot to update the HUD :/
For the "mode selection" text that is missing compared to the screenshot I have on imgur, I removed it on purpose as I find it unnecessary and also because I'm working on a new mode selection panel that will not feature that label (thanks for reporting it tho!)
And finally, yeah sometimes working on HUDs till 1 in the morning makes you invent new words lmao
I have since updated the HUD and hopefully fixed everything.
Thank you once more <3

**Comment by nternalz34** [comment]
While you are working on a big update, I _unexpectedly_ found some more bugs during gameplay. 😯 Since this HUD is my fav, I will try to help more.
(If you can, please do the bugs fixes in the big update instead of the current one. Saves time.)

- Not sure if this is about the "wide" size or the "xpos", but some map names are misaligned. (This is from a casual match.)
![image](https://user-images.githubusercontent.com/102655447/161583275-ef557db9-7d41-4dae-8faa-b9f2532385e3.png)

- If your concept is to make the energy bar in MvM to match with the Uber meter, then too bad that it doesn't work w/ Minimal HUD on.  It just.. looks not right. (Currently testing w/o Minimal HUD.. update later.)
![image](https://user-images.githubusercontent.com/102655447/161583764-9d7a60e5-99a4-4646-9da3-f2d56bea9f63.png)

- For long usernames, try to make the "wide" size a bit smaller since it's covering the level. (Ah.. yeah I have a long username. 😅)

- I can't see the level/rank on hudmatchsummary.res. (I barely even care about the top bar. ☹️)

**Comment by skaiTF** [comment]
Hi, I have since fixed all of the issues you mentioned (except the misalignment of the map and server names which will be addressed once I'm done with a new concept for those two I've been thinking about).
Since these issues do not compromise the user experience at a major level, they will only be featured in gamebanana for the major update unlike what happened with the last update which I made because the HUD crosshairs are, in my opinion, very important.
Thank you once more for the help finding these things. If you end up running into anything else, please open another issue. ❤️
